spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.1.251:3306/ydh-4?useUnicode=true&characterEncoding=utf8
    password: ydh20130815
logging:
  level:
    com.hey.justtest.dao: debug
